#!/usr/bin/env node
/**
 * Compile .art templates under phi-assets/html into JS factories
 */
import {
	existsSync,
	mkdirSync,
	readdirSync,
	readFileSync,
	statSync,
	writeFileSync,
} from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import template from "art-template";

const root = join(fileURLToPath(new URL("..", import.meta.url)));
const htmlRoot = join(root, "phi-assets/html");
const outFile = join(root, "src/phi/art-compiled.ts");

const origWarn = console.warn.bind(console);
console.warn = (...args) => {
	if (String(args[0] ?? "").includes("Template upgrade:")) return;
	origWarn(...args);
};

function walk(dir, out = []) {
	for (const name of readdirSync(dir)) {
		const p = join(dir, name);
		if (statSync(p).isDirectory()) walk(p, out);
		else if (name.endsWith(".art")) out.push(p);
	}
	return out;
}

if (!existsSync(htmlRoot)) {
	console.error(`precompile-art: missing ${htmlRoot}`);
	process.exit(1);
}

const files = walk(htmlRoot).sort();
const chunks = [
	"// @ts-nocheck",
	"/* generated by scripts/precompile-art.mjs — do not edit */",
	"export const artFactories = {",
];

for (const file of files) {
	const key = relative(htmlRoot, file).replaceAll("\\", "/");
	const source = readFileSync(file, "utf8");
	let inner;
	try {
		const render = template.compile({
			filename: file,
			source,
			minimize: false,
			cache: false,
			debug: false,
			compileDebug: false,
			escape: true,
		});
		inner = render.toString();
	} catch (err) {
		console.error(
			`precompile-art: ${key}: ${err instanceof Error ? err.message : err}`,
		);
		process.exit(1);
	}
	chunks.push(`  ${JSON.stringify(key)}: function ($imports, $$options) {`);
	chunks.push(`    return (${inner})`);
	chunks.push("  },");
}

chunks.push("}");
chunks.push("");

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, chunks.join("\n"));
console.log(
	`precompile-art: ${files.length} templates → ${relative(root, outFile)}`,
);
